version: 2
updates:
  # Dependabot uses the npm ecosystem for package.json/pnpm-lock.yaml projects.
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    versioning-strategy: increase
    groups:
      npm-minor-patch:
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 3
    labels:
      - dependencies
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 3
    labels:
      - dependencies
